name: Master Build

on: [push]

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version: [12]

        steps:
            - name: Checkout master
            - uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v1
              with:
                  version: ${{ matrix.node_version }}

            - name: Install dependencies
              run: npm i -D

            - name: Compile TypeScript
              run: npm run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  path: dist
