name: Master Build

on: [push]

jobs:
    build:
        name: "Build"
        runs-on: self-hosted
        strategy:
            matrix:
                node_version: [12]

        steps:
            - name: Checkout master
              uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v1
              with:
                  version: ${{ matrix.node_version }}

            - name: Install dependencies
              run: npm i -D

            - name: Compile TypeScript
              run: npm run build

            - name: Zip artifacts
              run: zip -r dist.zip dist package.json

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: My awesome program
                  path: dist.zip
            # - name: Discord notification
            #   env:
            #       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
            #   uses: Ilshidur/action-discord@master
            #   with:
            #       args: "{{ EVENT_PAYLOAD.repository.full_name }} has been built!"
